spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

    hikari:
      connection-timeout: 10000
      maximum-pool-size: 3

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: true
    database: postgresql

jwt:
  secret-key: ${JWT_SECRET}
  expiration: 2592000000
  refresh: 86400000